language: go
go:
        - 1.8.x
        - 1.9.x
        - 1.10.x
        - 1.11

install:
        - mkdir -p $HOME/gopath/src/
        - ln -s $HOME/gopath/src/github.com/baliance/gooxml $HOME/gopath/src/gooxml

script:
        - cd $HOME/gopath/src/gooxml
        - ./build-examples.sh
        - go vet ./...
        - go test ./...

after_success:
        - ./test-coverage.sh
